/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read API and database readiness */
        get: operations["getApiStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequestId: string;
        StatusResponse: {
            data: {
                /** @constant */
                service: "berufe-api";
                /** @constant */
                status: "ok";
            };
            request_id: components["schemas"]["RequestId"];
        };
        Error: {
            code: string;
            message: string;
            field_errors?: {
                [key: string]: string[];
            };
            request_id: components["schemas"]["RequestId"];
        };
        ErrorResponse: {
            error: components["schemas"]["Error"];
        };
        PageMeta: {
            page: number;
            per_page: number;
            total_count: number;
            total_pages: number;
        };
    };
    responses: never;
    parameters: {
        /** @description One-based result page. */
        Page: number;
        /** @description Result count per page. */
        PageSize: number;
        /** @description Endpoint-specific deterministic ordering key. */
        Order: string;
    };
    requestBodies: never;
    headers: {
        /** @description Bounded request identifier used for safe cross-service correlation. */
        RequestId: components["schemas"]["RequestId"];
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getApiStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and its database are ready. */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description The API cannot currently reach a required dependency. */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["RequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
